import { useState } from "react";

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    packages: "Packages",
    bookings: "Bookings",
    logout: "Logout",
    loading: "Loading...",

    // Dashboard
    totalPackages: "Total Packages",
    totalBookings: "Total Bookings",
    confirmedBookings: "Confirmed",
    pendingBookings: "Pending",
    recentBookings: "Recent Bookings",
    noBookingsYet: "No bookings yet",
    revenue: "Est. Revenue",
    viewAll: "View all",

    // Packages
    addPackage: "Add Package",
    editPackage: "Edit Package",
    packageName: "Package Name",
    destination: "Destination",
    duration: "Duration (days)",
    price: "Price (USD)",
    maxCapacity: "Max Capacity",
    category: "Category",
    highlights: "Highlights",
    highlightsHint: "(comma separated)",
    itinerary: "Itinerary",
    addDay: "+ Add Day",
    availableForBooking: "Available for booking",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    activate: "Activate",
    deactivate: "Deactivate",
    deletePackage: "Delete Package?",
    deleteConfirm: "This action cannot be undone.",
    packagesTotal: "packages total",
    noPackagesYet: "No packages yet",
    noPackagesHint: "Click \"Add Package\" to create your first one",
    any: "Any",
    spotsLeft: "spots left",
    perPerson: "/ person",
    days: "days",
    day: "Day",
    more: "more",
    saving: "Saving...",
    active: "Active",
    inactive: "Inactive",
    availability: "Availability",
    availabilityLabel: "Availability",

    // Bookings
    client: "Client",
    package: "Package",
    travelDate: "Travel Date",
    guests: "Guests",
    total: "Total",
    status: "Status",
    actions: "Actions",
    confirm: "Confirm",
    pending: "Pending",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    all: "All",
    beach: "Beach",
    city: "City",
    adventure: "Adventure",
    cultural: "Cultural",
    searchPlaceholder: "Search by client or package...",
    bookingsTotal: "bookings total",
    noBookingsFound: "No bookings found",
    noBookingsHint: "Try changing the filters",
    bookingDetails: "Booking Details",
    name: "Name",
    email: "Email",
    phone: "Phone",
    adults: "Adults",
    children: "Children",
    notes: "Notes",
    bookedOn: "Booked on",
    totalPrice: "Total Price",
    downloadPDF: "PDF",

    // Public
    discoverTitle: "Discover Your Next Adventure",
    discoverSubtitle: "Handcrafted travel packages for unforgettable experiences",
    categoryLabel: "Category",
    maxPrice: "Max Price (USD)",
    maxDays: "Max Days",
    resetFilters: "Reset filters",
    clearFilters: "Clear filters",
    packagesAvailable: "packages available",
    packageAvailable: "package available",
    noPackagesMatch: "No packages match your filters",
    bookNow: "Book Now →",

    // Booking form
    backToPackages: "← Back to packages",
    bookingFor: "Booking for",
    from: "from",
    yourDetails: "Your Details",
    tripDetails: "Trip Details",
    confirmation: "Confirmation",
    fullName: "Full Name",
    emailAddress: "Email Address",
    phoneNumber: "Phone Number",
    preferredDate: "Preferred Travel Date",
    specialRequests: "Special Requests / Notes",
    specialRequestsHint: "Dietary requirements, special occasions, accessibility needs...",
    adultsLabel: "Adults",
    childrenLabel: "Children",
    childrenHint: "(50% price)",
    pricePreview: "Price Summary",
    bookingSummary: "Booking Summary",
    byConfirming: "By confirming, our team will contact you within 24 hours to finalize your booking.",
    back: "← Back",
    previous: "← Previous",
    next: "Next →",
    confirmBooking: "✅ Confirm Booking",
    submitting: "Submitting...",
    packageNotFound: "Package not found.",

    // Success
    bookingConfirmed: "Booking Confirmed!",
    thankYou: "Thank you",
    bookingReceived: "Your booking has been received. Our team will contact you at",
    bookingReceivedEnd: "shortly.",
    backToPackagesBtn: "← Back to Packages",

    // PDF
    pdfTitle: "Travel Booking Confirmation",
    pdfRef: "Ref:",
    pdfDate: "Date:",
    pdfClientInfo: "Client Information",
    pdfClientName: "Name:",
    pdfClientEmail: "Email:",
    pdfClientPhone: "Phone:",
    pdfClientTravel: "Travel:",
    pdfDetail: "Detail",
    pdfValue: "Value",
    pdfPackage: "Package",
    pdfDestination: "Destination",
    pdfDuration: "Duration",
    pdfDurationUnit: "days",
    pdfAdults: "Adults",
    pdfChildren: "Children",
    pdfTravelDate: "Travel Date",
    pdfCategory: "Category",
    pdfPriceBreakdown: "Price Breakdown",
    pdfAmount: "Amount (USD)",
    pdfTotal: "TOTAL",
    pdfHighlights: "Package Highlights",
    pdfSpecialRequests: "Special Requests",
    pdfFooter: "TourFlow — Your trusted travel partner",
    conversion: "conversion",
    confirmedOnly: "confirmed bookings only",
  },

  ro: {
    // Navigation
    dashboard: "Panou Principal",
    packages: "Pachete",
    bookings: "Rezervări",
    logout: "Deconectare",
    loading: "Se încarcă...",

    // Dashboard
    totalPackages: "Total Pachete",
    totalBookings: "Total Rezervări",
    confirmedBookings: "Confirmate",
    pendingBookings: "În așteptare",
    recentBookings: "Rezervări Recente",
    noBookingsYet: "Nicio rezervare încă",
    revenue: "Venit Est.",
    viewAll: "Vezi toate",

    // Packages
    addPackage: "+ Adaugă Pachet",
    editPackage: "Editează Pachet",
    packageName: "Nume Pachet",
    destination: "Destinație",
    duration: "Durată (zile)",
    price: "Preț (USD)",
    maxCapacity: "Capacitate Max",
    category: "Categorie",
    highlights: "Puncte Cheie",
    highlightsHint: "(separate prin virgulă)",
    itinerary: "Itinerar",
    addDay: "+ Adaugă Zi",
    availableForBooking: "Disponibil pentru rezervare",
    saveChanges: "Salvează",
    cancel: "Anulează",
    delete: "Șterge",
    edit: "Editează",
    activate: "Activează",
    deactivate: "Dezactivează",
    deletePackage: "Ștergi pachetul?",
    deleteConfirm: "Această acțiune nu poate fi anulată.",
    packagesTotal: "pachete total",
    noPackagesYet: "Niciun pachet încă",
    noPackagesHint: "Apasă \"Adaugă Pachet\" pentru a crea primul",
    any: "Orice",
    spotsLeft: "locuri disponibile",
    perPerson: "/ persoană",
    days: "zile",
    day: "Ziua",
    more: "mai multe",
    saving: "Se salvează...",
    active: "Activ",
    inactive: "Inactiv",
    availability: "Disponibilitate",
    availabilityLabel: "Disponibilitate",

    // Bookings
    client: "Client",
    package: "Pachet",
    travelDate: "Data Călătoriei",
    guests: "Persoane",
    total: "Total",
    status: "Status",
    actions: "Acțiuni",
    confirm: "Confirmă",
    pending: "În așteptare",
    confirmed: "Confirmat",
    cancelled: "Anulat",
    all: "Toate",
    beach: "Plajă",
    city: "Oraș",
    adventure: "Aventură",
    cultural: "Cultural",
    searchPlaceholder: "Caută după client sau pachet...",
    bookingsTotal: "rezervări total",
    noBookingsFound: "Nicio rezervare găsită",
    noBookingsHint: "Încearcă să schimbi filtrele",
    bookingDetails: "Detalii Rezervare",
    name: "Nume",
    email: "Email",
    phone: "Telefon",
    adults: "Adulți",
    children: "Copii",
    notes: "Notițe",
    bookedOn: "Rezervat pe",
    totalPrice: "Preț Total",
    downloadPDF: "PDF",

    // Public
    discoverTitle: "Descoperă Următoarea Ta Aventură",
    discoverSubtitle: "Pachete turistice create cu grijă pentru experiențe de neuitat",
    categoryLabel: "Categorie",
    maxPrice: "Preț Maxim (USD)",
    maxDays: "Zile Max",
    resetFilters: "Resetează filtrele",
    clearFilters: "Șterge filtrele",
    packagesAvailable: "pachete disponibile",
    packageAvailable: "pachet disponibil",
    noPackagesMatch: "Niciun pachet nu corespunde filtrelor",
    bookNow: "Rezervă Acum →",

    // Booking form
    backToPackages: "← Înapoi la pachete",
    bookingFor: "Rezervare pentru",
    from: "de la",
    yourDetails: "Datele Tale",
    tripDetails: "Detalii Călătorie",
    confirmation: "Confirmare",
    fullName: "Nume Complet",
    emailAddress: "Adresă Email",
    phoneNumber: "Număr Telefon",
    preferredDate: "Data Preferată de Călătorie",
    specialRequests: "Cereri Speciale / Notițe",
    specialRequestsHint: "Cerințe alimentare, ocazii speciale, nevoi de accesibilitate...",
    adultsLabel: "Adulți",
    childrenLabel: "Copii",
    childrenHint: "(50% preț)",
    pricePreview: "Sumar Preț",
    bookingSummary: "Sumar Rezervare",
    byConfirming: "Prin confirmare, echipa noastră vă va contacta în 24 de ore pentru a finaliza rezervarea.",
    back: "← Înapoi",
    previous: "← Anterior",
    next: "Înainte →",
    confirmBooking: "✅ Confirmă Rezervarea",
    submitting: "Se trimite...",
    packageNotFound: "Pachetul nu a fost găsit.",

    // Success
    bookingConfirmed: "Rezervare Confirmată!",
    thankYou: "Mulțumim",
    bookingReceived: "Rezervarea ta a fost primită. Echipa noastră te va contacta la",
    bookingReceivedEnd: "în curând.",
    backToPackagesBtn: "← Înapoi la Pachete",

    // PDF
    pdfTitle: "Confirmare Rezervare",
    pdfRef: "Ref:",
    pdfDate: "Data:",
    pdfClientInfo: "Informatii Client",
    pdfClientName: "Nume:",
    pdfClientEmail: "Email:",
    pdfClientPhone: "Telefon:",
    pdfClientTravel: "Calatorie:",
    pdfDetail: "Detaliu",
    pdfValue: "Valoare",
    pdfPackage: "Pachet",
    pdfDestination: "Destinatie",
    pdfDuration: "Durata",
    pdfDurationUnit: "zile",
    pdfAdults: "Adulti",
    pdfChildren: "Copii",
    pdfTravelDate: "Data Calatoriei",
    pdfCategory: "Categorie",
    pdfPriceBreakdown: "Detalii Pret",
    pdfAmount: "Suma (USD)",
    pdfTotal: "TOTAL",
    pdfHighlights: "Puncte Cheie",
    pdfSpecialRequests: "Cereri Speciale",
    pdfFooter: "TourFlow — Partenerul tau de incredere",
    conversion: "conversie",
    confirmedOnly: "doar rezervări confirmate",
  },
};

// Singleton store — acelasi lang in toata aplicatia, persistat in localStorage
let currentLang = localStorage.getItem("tourflow_lang") || "en";
const listeners = new Set();

function setLang(lang) {
  currentLang = lang;
  localStorage.setItem("tourflow_lang", lang);
  listeners.forEach((fn) => fn(lang));
}

export function useLanguage() {
  const [lang, setLangState] = useState(currentLang);

  useState(() => {
    const handler = (l) => setLangState(l);
    listeners.add(handler);
    return () => listeners.delete(handler);
  });

  const t = (key) => translations[lang][key] ?? key;
  const toggleLang = () => setLang(lang === "en" ? "ro" : "en");

  return { lang, t, toggleLang };
}